step1 fork and python environment
gr0und-s3ct0r/gr0und-s3ct0r.github.io pull request #24
Opened 2017-10-16 20:10 UTC by 4383

explain how to setup fork and clone and how to setup python environment

2017-10-21 21:44 UTC, dj4ngo commented on _drafts/contribute-to-ansible.markdown
> +First, go to the [ansible github official page](https://github.com/ansible/ansible) and click on the fork button.
Take some snapshots for final article it you can

2017-10-21 21:47 UTC, dj4ngo requested changes

2017-10-21 21:47 UTC, dj4ngo commented on _drafts/contribute-to-ansible.markdown
> +$ git config --global user.email "<your-email@example.com>"
You should need to add the config push.default method (simple or matching)

2017-10-21 21:47 UTC, dj4ngo commented on _drafts/contribute-to-ansible.markdown
> +For working on bugfix, tests, or new features you need to install specific requirements:
To work on bugfix.....

2017-10-24 09:22 UTC, 4383 commented
@dj4ngo fix review done!

2017-10-24 13:06 UTC, dj4ngo approved these changes

2017-10-24 13:06 UTC, merged